// Generated by HLC 4.3.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/Counter.h>

void Counter_new(Counter r0,int r1) {
	r0->value = r1;
	return;
}

void Counter_increment(Counter r0) {
	int r1;
	r1 = r0->value;
	++r1;
	r0->value = r1;
	return;
}

int Counter_getValue(Counter r0) {
	int r1;
	r1 = r0->value;
	return r1;
}

