// Generated by HLC 4.3.3 (HL v4)
#ifndef INC__std__Counter
#define INC__std__Counter
typedef struct _$Counter *$Counter;
typedef struct _Counter *Counter;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$Counter {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _Counter {
	hl_type *$type;
	int value;
};
#endif

