// Generated by HLC 4.3.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <_std/HelloWorld.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log g$_haxe_Log;
extern String s$f9fd255;
extern String s$HelloWorld_hx;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$HelloWorld;
extern String s$main;
extern hl_type t$vrt_eaa6a3b;
extern String s$41f0b90;
extern String s$Math_test_;
#include <hl/natives.h>
String String___alloc__(vbyte*,int);
String String___add__(String,String);
extern String s$193eba1;
extern String s$fcacca1;
extern String s$6999ae0;

void HelloWorld_main() {
	vdynobj *r4;
	String r3, r5;
	vvirtual *r7;
	haxe__$Log r2;
	vclosure *r1;
	int *r10;
	vbyte *r11;
	int r6, r8, r9;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$f9fd255;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HelloWorld_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 3;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HelloWorld;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$41f0b90;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HelloWorld_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r6 = 4;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r6);
	r5 = (String)s$HelloWorld;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r6 = 10;
	r8 = 32;
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$Math_test_;
	r9 = r6;
	r10 = &r9;
	r11 = hl_itos(r9,r10);
	r5 = String___alloc__(r11,r9);
	r3 = String___add__(r3,r5);
	r5 = (String)s$193eba1;
	r3 = String___add__(r3,r5);
	r9 = r8;
	r10 = &r9;
	r11 = hl_itos(r9,r10);
	r5 = String___alloc__(r11,r9);
	r3 = String___add__(r3,r5);
	r5 = (String)s$fcacca1;
	r3 = String___add__(r3,r5);
	r9 = r6 + r8;
	r10 = &r9;
	r11 = hl_itos(r9,r10);
	r5 = String___alloc__(r11,r9);
	r3 = String___add__(r3,r5);
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HelloWorld_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r9 = 8;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r9);
	r5 = (String)s$HelloWorld;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	r2 = (haxe__$Log)g$_haxe_Log;
	r1 = r2->trace;
	if( r1 == NULL ) hl_null_access();
	r3 = (String)s$6999ae0;
	r4 = hl_alloc_dynobj();
	r5 = (String)s$HelloWorld_hx;
	hl_dyn_setp((vdynamic*)r4,37969014/*fileName*/,&t$String,r5);
	r9 = 10;
	hl_dyn_seti((vdynamic*)r4,371360620/*lineNumber*/,&t$_i32,r9);
	r5 = (String)s$HelloWorld;
	hl_dyn_setp((vdynamic*)r4,-63073762/*className*/,&t$String,r5);
	r5 = (String)s$main;
	hl_dyn_setp((vdynamic*)r4,302979532/*methodName*/,&t$String,r5);
	r7 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r4);
	r1->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r1->fun)((vdynamic*)r1->value,((vdynamic*)r3),r7) : ((void (*)(vdynamic*,vvirtual*))r1->fun)(((vdynamic*)r3),r7);
	return;
}

