// Generated by HLC 4.3.3 (HL v4)
#ifndef INC__std__HelloWorld
#define INC__std__HelloWorld
typedef struct _$HelloWorld *$HelloWorld;
typedef struct _HelloWorld *HelloWorld;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$HelloWorld {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* main;
};
struct _HelloWorld {
	hl_type *$type;
};
#endif

