// Generated by HLC 4.3.3 (HL v4)
#ifndef INC__std__Test
#define INC__std__Test
typedef struct _$Test *$Test;
typedef struct _Test *Test;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _$Test {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* main;
	vclosure* square;
	vclosure* riskyOperation;
};
struct _Test {
	hl_type *$type;
};
#endif

