// Generated by HLC 4.3.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <hl/BaseType.h>
#include <hl/Class.h>
#include <_std/String.h>
#include <hl/types/ArrayAccess.h>
#include <hl/types/ArrayBase.h>
#include <haxe/Log.h>
#include <_std/WasmCanvas.h>
#include <_std/CanvasTest.h>
#include <sys/thread/_EventLoop/RegularEvent.h>
#include <sys/thread/Lock.h>
#include <sys/thread/EventLoop.h>
#include <sys/thread/_Thread/HaxeThread.h>
#include <haxe/Timer.h>
#include <_std/Math.h>
#include <_std/Date.h>
#include <_std/StringBuf.h>
#include <_std/SysError.h>
#include <hl/natives.h>
#include <hl/Enum.h>
#include <haxe/Exception.h>
#include <sys/thread/NoEventLoopException.h>
#include <haxe/MainEvent.h>
#include <haxe/MainLoop.h>
#include <haxe/exceptions/PosException.h>
#include <haxe/exceptions/NotImplementedException.h>
#include <haxe/iterators/ArrayIterator.h>
#include <haxe/iterators/ArrayKeyValueIterator.h>
#include <hl/NativeArrayIterator_Dynamic.h>
#include <hl/NativeArrayIterator_Int.h>
#include <haxe/io/Error.h>
#include <hl/types/BytesIterator_Float.h>
#include <hl/types/BytesIterator_Int.h>
#include <hl/types/BytesIterator_hl_F32.h>
#include <hl/types/BytesIterator_hl_UI16.h>
#include <hl/types/ArrayDynIterator.h>
#include <hl/types/ArrayObjIterator.h>
#include <_std/Std.h>
#include <hl/CoreType.h>
#include <hl/CoreEnum.h>
#include <hl/_Bytes/Bytes_Impl_.h>
#include <_std/Sys.h>
#include <_std/Type.h>
#include <sys/thread/_Thread/Thread_Impl_.h>
#include <sys/thread/_Mutex/Mutex_Impl_.h>
#include <haxe/EntryPoint.h>
#include <haxe/NativeStackTrace.h>
#include <haxe/ds/ArraySort.h>
#include <hl/_NativeArray/NativeArray_Impl_.h>
#include <hl/_Type/Type_Impl_.h>
#include <hl/types/ArrayDyn.h>
#include <hl/types/_BytesMap/BytesMap_Impl_.h>
extern hl_type t$String;
extern vbyte string$115c6dd[];

// Globals
hl__$BaseType g$_hl_BaseType = 0;
hl__Class g$_hl_Class = 0;
$String g$_String = 0;
hl__types__$ArrayAccess g$_hl_types_ArrayAccess = 0;
hl__types__$ArrayBase g$_hl_types_ArrayBase = 0;
haxe__$Log g$_haxe_Log = 0;
String s$_Canvas_2D_Graphics_Test_ = 0;
String s$CanvasTest_hx = 0;
String s$CanvasTest = 0;
String s$main = 0;
String s$Initializing_canvas_ = 0;
$WasmCanvas g$_WasmCanvas = 0;
$CanvasTest g$_CanvasTest = 0;
String s$gameCanvas = 0;
String s$Starting_animation_loop_ = 0;
sys__thread___EventLoop__$RegularEvent g$deb90ea = 0;
sys__thread__$Lock g$_sys_thread_Lock = 0;
sys__thread__$EventLoop g$_sys_thread_EventLoop = 0;
sys__thread___Thread__$HaxeThread g$_sys_thread__Thread_HaxeThread = 0;
haxe__$Timer g$_haxe_Timer = 0;
$Math g$_Math = 0;
String s$HashLink_WASM_Canvas_2D_Demo = 0;
String s$Frame_ = 0;
String s$60_FPS = 0;
String s$Ball_ = 0;
String s$fc763cb = 0;
String s$9371d7a = 0;
$Date g$_Date = 0;
String s$Can_t_add_ = 0;
String s$84c4047 = 0;
String s$_and_ = 0;
String s$Invalid_unicode_char_ = 0;
String s$null = 0;
String s$ = 0;
$StringBuf g$_StringBuf = 0;
$SysError g$_SysError = 0;
String s$SysError_ = 0;
String s$68b329d = 0;
hl_bytes_map* g$__types__ = 0;
hl__$Enum g$_hl_Enum = 0;
haxe__$Exception g$_haxe_Exception = 0;
sys__thread__$NoEventLoopException g$_sys_thread_NoEventLoopException = 0;
String s$853ae90 = 0;
String s$e265492 = 0;
haxe__$MainEvent g$_haxe_MainEvent = 0;
haxe__$MainLoop g$_haxe_MainLoop = 0;
haxe__exceptions__$PosException g$_haxe_exceptions_PosException = 0;
String s$_unknown_ = 0;
String s$_in_ = 0;
String s$5058f1a = 0;
String s$_at_ = 0;
haxe__exceptions__$NotImplementedException g$c9feed3 = 0;
String s$Not_implemented = 0;
haxe__iterators__$ArrayIterator g$_haxe_iterators_ArrayIterator = 0;
haxe__iterators__$ArrayKeyValueIterator g$19142ef = 0;
hl__$NativeArrayIterator_Dynamic g$_hl_NativeArrayIterator_Dynamic = 0;
hl__$NativeArrayIterator_Int g$_hl_NativeArrayIterator_Int = 0;
String s$hl_types_ArrayBase_hx = 0;
String s$hl_types_ArrayAccess = 0;
String s$getDyn = 0;
String s$setDyn = 0;
String s$blit = 0;
String s$hl_types_ArrayBase = 0;
String s$pushDyn = 0;
String s$popDyn = 0;
String s$shiftDyn = 0;
String s$unshiftDyn = 0;
String s$insertDyn = 0;
String s$containsDyn = 0;
String s$removeDyn = 0;
String s$sortDyn = 0;
String s$slice = 0;
String s$splice = 0;
String s$join = 0;
String s$reverse = 0;
String s$resize = 0;
String s$toString = 0;
haxe__io__$Error g$haxe_io_Error = 0;
venum* g$haxe_io_Error_OutsideBounds = 0;
hl__types__$BytesIterator_Float g$_hl_types_BytesIterator_Float = 0;
String s$Invalid_array_index_ = 0;
hl__types__$BytesIterator_Int g$_hl_types_BytesIterator_Int = 0;
hl__types__$BytesIterator_hl_F32 g$_hl_types_BytesIterator_hl_F32 = 0;
hl__types__$BytesIterator_hl_UI16 g$_hl_types_BytesIterator_hl_UI16 = 0;
hl__types__$ArrayDynIterator g$_hl_types_ArrayDynIterator = 0;
hl__types__$ArrayObjIterator g$_hl_types_ArrayObjIterator = 0;
$Std g$_Std = 0;
String s$2f43b42 = 0;
String s$115c6dd = 0;
hl__CoreType g$_Float = 0;
String s$Float = 0;
hl__CoreType g$_Int = 0;
String s$Int = 0;
hl__CoreEnum g$_Bool = 0;
String s$Bool = 0;
hl__CoreType g$_Dynamic = 0;
String s$Dynamic = 0;
hl___Bytes__$Bytes_Impl_ g$_hl__Bytes_Bytes_Impl_ = 0;
$Sys g$_Sys = 0;
$Type g$_Type = 0;
sys__thread___Thread__$Thread_Impl_ g$_sys_thread__Thread_Thread_Impl_ = 0;
sys__thread___Mutex__$Mutex_Impl_ g$_sys_thread__Mutex_Mutex_Impl_ = 0;
haxe__$EntryPoint g$_haxe_EntryPoint = 0;
haxe__$NativeStackTrace g$_haxe_NativeStackTrace = 0;
haxe__ds__$ArraySort g$_haxe_ds_ArraySort = 0;
venum* g$haxe_io_Error_Blocked = 0;
venum* g$haxe_io_Error_Overflow = 0;
hl___NativeArray__$NativeArray_Impl_ g$7abf311 = 0;
hl___Type__$Type_Impl_ g$_hl__Type_Type_Impl_ = 0;
String s$Array = 0;
hl__types__$ArrayDyn g$_hl_types_ArrayDyn = 0;
String s$hl_types_ArrayDyn = 0;
hl__types___BytesMap__$BytesMap_Impl_ g$2c4fafe = 0;
static struct _String const_s$_Canvas_2D_Graphics_Test_ = {&t$String,(vbyte*)USTR("=== Canvas 2D Graphics Test ==="),31};
static struct _String const_s$CanvasTest_hx = {&t$String,(vbyte*)USTR("CanvasTest.hx"),13};
static struct _String const_s$CanvasTest = {&t$String,(vbyte*)USTR("CanvasTest"),10};
static struct _String const_s$main = {&t$String,(vbyte*)USTR("main"),4};
static struct _String const_s$Initializing_canvas_ = {&t$String,(vbyte*)USTR("Initializing canvas..."),22};
static struct _String const_s$gameCanvas = {&t$String,(vbyte*)USTR("gameCanvas"),10};
static struct _String const_s$Starting_animation_loop_ = {&t$String,(vbyte*)USTR("Starting animation loop..."),26};
static struct _String const_s$HashLink_WASM_Canvas_2D_Demo = {&t$String,(vbyte*)USTR("HashLink WASM - Canvas 2D Demo"),30};
static struct _String const_s$Frame_ = {&t$String,(vbyte*)USTR("Frame: "),7};
static struct _String const_s$60_FPS = {&t$String,(vbyte*)USTR("60 FPS"),6};
static struct _String const_s$Ball_ = {&t$String,(vbyte*)USTR("Ball: ("),7};
static struct _String const_s$fc763cb = {&t$String,(vbyte*)USTR(", "),2};
static struct _String const_s$9371d7a = {&t$String,(vbyte*)USTR(")"),1};
static struct _String const_s$Can_t_add_ = {&t$String,(vbyte*)USTR("Can't add "),10};
static struct _String const_s$84c4047 = {&t$String,(vbyte*)USTR("("),1};
static struct _String const_s$_and_ = {&t$String,(vbyte*)USTR(") and "),6};
static struct _String const_s$Invalid_unicode_char_ = {&t$String,(vbyte*)USTR("Invalid unicode char "),21};
static struct _String const_s$null = {&t$String,(vbyte*)USTR("null"),4};
static struct _String const_s$ = {&t$String,(vbyte*)USTR(""),0};
static struct _String const_s$SysError_ = {&t$String,(vbyte*)USTR("SysError("),9};
static struct _String const_s$68b329d = {&t$String,(vbyte*)USTR("\n"),1};
static struct _String const_s$853ae90 = {&t$String,(vbyte*)USTR(":"),1};
static struct _String const_s$e265492 = {&t$String,(vbyte*)USTR(": "),2};
static struct _String const_s$_unknown_ = {&t$String,(vbyte*)USTR("(unknown)"),9};
static struct _String const_s$_in_ = {&t$String,(vbyte*)USTR(" in "),4};
static struct _String const_s$5058f1a = {&t$String,(vbyte*)USTR("."),1};
static struct _String const_s$_at_ = {&t$String,(vbyte*)USTR(" at "),4};
static struct _String const_s$Not_implemented = {&t$String,(vbyte*)USTR("Not implemented"),15};
static struct _String const_s$hl_types_ArrayBase_hx = {&t$String,(vbyte*)USTR("hl/types/ArrayBase.hx"),21};
static struct _String const_s$hl_types_ArrayAccess = {&t$String,(vbyte*)USTR("hl.types.ArrayAccess"),20};
static struct _String const_s$getDyn = {&t$String,(vbyte*)USTR("getDyn"),6};
static struct _String const_s$setDyn = {&t$String,(vbyte*)USTR("setDyn"),6};
static struct _String const_s$blit = {&t$String,(vbyte*)USTR("blit"),4};
static struct _String const_s$hl_types_ArrayBase = {&t$String,(vbyte*)USTR("hl.types.ArrayBase"),18};
static struct _String const_s$pushDyn = {&t$String,(vbyte*)USTR("pushDyn"),7};
static struct _String const_s$popDyn = {&t$String,(vbyte*)USTR("popDyn"),6};
static struct _String const_s$shiftDyn = {&t$String,(vbyte*)USTR("shiftDyn"),8};
static struct _String const_s$unshiftDyn = {&t$String,(vbyte*)USTR("unshiftDyn"),10};
static struct _String const_s$insertDyn = {&t$String,(vbyte*)USTR("insertDyn"),9};
static struct _String const_s$containsDyn = {&t$String,(vbyte*)USTR("containsDyn"),11};
static struct _String const_s$removeDyn = {&t$String,(vbyte*)USTR("removeDyn"),9};
static struct _String const_s$sortDyn = {&t$String,(vbyte*)USTR("sortDyn"),7};
static struct _String const_s$slice = {&t$String,(vbyte*)USTR("slice"),5};
static struct _String const_s$splice = {&t$String,(vbyte*)USTR("splice"),6};
static struct _String const_s$join = {&t$String,(vbyte*)USTR("join"),4};
static struct _String const_s$reverse = {&t$String,(vbyte*)USTR("reverse"),7};
static struct _String const_s$resize = {&t$String,(vbyte*)USTR("resize"),6};
static struct _String const_s$toString = {&t$String,(vbyte*)USTR("toString"),8};
static struct _String const_s$Invalid_array_index_ = {&t$String,(vbyte*)USTR("Invalid array index "),20};
static struct _String const_s$2f43b42 = {&t$String,(vbyte*)USTR("..."),3};
static struct _String const_s$115c6dd = {&t$String,(vbyte*)string$115c6dd,73};
static struct _String const_s$Float = {&t$String,(vbyte*)USTR("Float"),5};
static struct _String const_s$Int = {&t$String,(vbyte*)USTR("Int"),3};
static struct _String const_s$Bool = {&t$String,(vbyte*)USTR("Bool"),4};
static struct _String const_s$Dynamic = {&t$String,(vbyte*)USTR("Dynamic"),7};
static struct _String const_s$Array = {&t$String,(vbyte*)USTR("Array"),5};
static struct _String const_s$hl_types_ArrayDyn = {&t$String,(vbyte*)USTR("hl.types.ArrayDyn"),17};

void hl_init_roots() {
	s$_Canvas_2D_Graphics_Test_ = &const_s$_Canvas_2D_Graphics_Test_;
	s$CanvasTest_hx = &const_s$CanvasTest_hx;
	s$CanvasTest = &const_s$CanvasTest;
	s$main = &const_s$main;
	s$Initializing_canvas_ = &const_s$Initializing_canvas_;
	s$gameCanvas = &const_s$gameCanvas;
	s$Starting_animation_loop_ = &const_s$Starting_animation_loop_;
	s$HashLink_WASM_Canvas_2D_Demo = &const_s$HashLink_WASM_Canvas_2D_Demo;
	s$Frame_ = &const_s$Frame_;
	s$60_FPS = &const_s$60_FPS;
	s$Ball_ = &const_s$Ball_;
	s$fc763cb = &const_s$fc763cb;
	s$9371d7a = &const_s$9371d7a;
	s$Can_t_add_ = &const_s$Can_t_add_;
	s$84c4047 = &const_s$84c4047;
	s$_and_ = &const_s$_and_;
	s$Invalid_unicode_char_ = &const_s$Invalid_unicode_char_;
	s$null = &const_s$null;
	s$ = &const_s$;
	s$SysError_ = &const_s$SysError_;
	s$68b329d = &const_s$68b329d;
	s$853ae90 = &const_s$853ae90;
	s$e265492 = &const_s$e265492;
	s$_unknown_ = &const_s$_unknown_;
	s$_in_ = &const_s$_in_;
	s$5058f1a = &const_s$5058f1a;
	s$_at_ = &const_s$_at_;
	s$Not_implemented = &const_s$Not_implemented;
	s$hl_types_ArrayBase_hx = &const_s$hl_types_ArrayBase_hx;
	s$hl_types_ArrayAccess = &const_s$hl_types_ArrayAccess;
	s$getDyn = &const_s$getDyn;
	s$setDyn = &const_s$setDyn;
	s$blit = &const_s$blit;
	s$hl_types_ArrayBase = &const_s$hl_types_ArrayBase;
	s$pushDyn = &const_s$pushDyn;
	s$popDyn = &const_s$popDyn;
	s$shiftDyn = &const_s$shiftDyn;
	s$unshiftDyn = &const_s$unshiftDyn;
	s$insertDyn = &const_s$insertDyn;
	s$containsDyn = &const_s$containsDyn;
	s$removeDyn = &const_s$removeDyn;
	s$sortDyn = &const_s$sortDyn;
	s$slice = &const_s$slice;
	s$splice = &const_s$splice;
	s$join = &const_s$join;
	s$reverse = &const_s$reverse;
	s$resize = &const_s$resize;
	s$toString = &const_s$toString;
	s$Invalid_array_index_ = &const_s$Invalid_array_index_;
	s$2f43b42 = &const_s$2f43b42;
	s$115c6dd = &const_s$115c6dd;
	s$Float = &const_s$Float;
	s$Int = &const_s$Int;
	s$Bool = &const_s$Bool;
	s$Dynamic = &const_s$Dynamic;
	s$Array = &const_s$Array;
	s$hl_types_ArrayDyn = &const_s$hl_types_ArrayDyn;
	hl_add_root((void**)&g$_hl_BaseType);
	hl_add_root((void**)&g$_hl_Class);
	hl_add_root((void**)&g$_String);
	hl_add_root((void**)&g$_hl_types_ArrayAccess);
	hl_add_root((void**)&g$_hl_types_ArrayBase);
	hl_add_root((void**)&g$_haxe_Log);
	hl_add_root((void**)&g$_WasmCanvas);
	hl_add_root((void**)&g$_CanvasTest);
	hl_add_root((void**)&g$deb90ea);
	hl_add_root((void**)&g$_sys_thread_Lock);
	hl_add_root((void**)&g$_sys_thread_EventLoop);
	hl_add_root((void**)&g$_sys_thread__Thread_HaxeThread);
	hl_add_root((void**)&g$_haxe_Timer);
	hl_add_root((void**)&g$_Math);
	hl_add_root((void**)&g$_Date);
	hl_add_root((void**)&g$_StringBuf);
	hl_add_root((void**)&g$_SysError);
	hl_add_root((void**)&g$__types__);
	hl_add_root((void**)&g$_hl_Enum);
	hl_add_root((void**)&g$_haxe_Exception);
	hl_add_root((void**)&g$_sys_thread_NoEventLoopException);
	hl_add_root((void**)&g$_haxe_MainEvent);
	hl_add_root((void**)&g$_haxe_MainLoop);
	hl_add_root((void**)&g$_haxe_exceptions_PosException);
	hl_add_root((void**)&g$c9feed3);
	hl_add_root((void**)&g$_haxe_iterators_ArrayIterator);
	hl_add_root((void**)&g$19142ef);
	hl_add_root((void**)&g$_hl_NativeArrayIterator_Dynamic);
	hl_add_root((void**)&g$_hl_NativeArrayIterator_Int);
	hl_add_root((void**)&g$haxe_io_Error);
	hl_add_root((void**)&g$haxe_io_Error_OutsideBounds);
	hl_add_root((void**)&g$_hl_types_BytesIterator_Float);
	hl_add_root((void**)&g$_hl_types_BytesIterator_Int);
	hl_add_root((void**)&g$_hl_types_BytesIterator_hl_F32);
	hl_add_root((void**)&g$_hl_types_BytesIterator_hl_UI16);
	hl_add_root((void**)&g$_hl_types_ArrayDynIterator);
	hl_add_root((void**)&g$_hl_types_ArrayObjIterator);
	hl_add_root((void**)&g$_Std);
	hl_add_root((void**)&g$_Float);
	hl_add_root((void**)&g$_Int);
	hl_add_root((void**)&g$_Bool);
	hl_add_root((void**)&g$_Dynamic);
	hl_add_root((void**)&g$_hl__Bytes_Bytes_Impl_);
	hl_add_root((void**)&g$_Sys);
	hl_add_root((void**)&g$_Type);
	hl_add_root((void**)&g$_sys_thread__Thread_Thread_Impl_);
	hl_add_root((void**)&g$_sys_thread__Mutex_Mutex_Impl_);
	hl_add_root((void**)&g$_haxe_EntryPoint);
	hl_add_root((void**)&g$_haxe_NativeStackTrace);
	hl_add_root((void**)&g$_haxe_ds_ArraySort);
	hl_add_root((void**)&g$haxe_io_Error_Blocked);
	hl_add_root((void**)&g$haxe_io_Error_Overflow);
	hl_add_root((void**)&g$7abf311);
	hl_add_root((void**)&g$_hl__Type_Type_Impl_);
	hl_add_root((void**)&g$_hl_types_ArrayDyn);
	hl_add_root((void**)&g$2c4fafe);
}
// Event loop is not available. Refer to sys.thread.Thread.runW...
vbyte string$115c6dd[] = {69,0,118,0,101,0,110,0,116,0,32,0,108,0,111,0,111,0,112,0,32,0,105,0,115,0,32,0,110,0,111,0,116,0,32,0,97,0,118,0,97,0,105,0,108,0,97,0,98,0,108,0,101,0,46,0,32,0,82,0,101,0,102,0,101,0,114,0,32,0,116,0,111,0,32,0,115,0,121,0,115,0,46,0,116,0,104,0,114,0,101,0,97,0,100,0,46,0,84,0,104,0,114,0,101,0,97,0,100,0,46,0,114,0,117,0,110,0,87,0,105,0,116,0,104,0,69\
	,0,118,0,101,0,110,0,116,0,76,0,111,0,111,0,112,0,46,0,0,0};
