// Generated by HLC 4.3.3 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/Timer.h>
#include <sys/thread/EventLoop.h>
void haxe_Timer_run(haxe__Timer);
extern hl_type t$fun_66d087d;
sys__thread___Thread__HaxeThread sys_thread__Thread_Thread_Impl__current(void);
sys__thread__EventLoop sys_thread__Thread_Thread_Impl__get_events(sys__thread___Thread__HaxeThread);
sys__thread___EventLoop__RegularEvent sys_thread_EventLoop_repeat(sys__thread__EventLoop,vclosure*,int);

void haxe_Timer_new__$1(haxe__Timer r0) {
	vclosure *r2;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->run;
	if( r2 == NULL ) hl_null_access();
	r2->hasValue ? ((void (*)(vdynamic*))r2->fun)((vdynamic*)r2->value) : ((void (*)(void))r2->fun)();
	return;
}

void haxe_Timer_new(haxe__Timer r0,int r1) {
	sys__thread___Thread__HaxeThread r4;
	sys__thread__EventLoop r6;
	sys__thread___EventLoop__RegularEvent r5;
	vclosure *r2;
	r2 = r0->run;
	if( r2 ) goto label$dcfb79f_2_4;
	r2 = hl_alloc_closure_ptr(&t$fun_66d087d,haxe_Timer_run,r0);
	r0->run = r2;
	label$dcfb79f_2_4:
	r4 = sys_thread__Thread_Thread_Impl__current();
	r0->thread = r4;
	r4 = r0->thread;
	r6 = sys_thread__Thread_Thread_Impl__get_events(r4);
	if( r6 == NULL ) hl_null_access();
	r2 = hl_alloc_closure_ptr(&t$fun_66d087d,haxe_Timer_new__$1,r0);
	r5 = sys_thread_EventLoop_repeat(r6,r2,r1);
	r0->eventHandler = r5;
	return;
}

void haxe_Timer_run(haxe__Timer r0) {
	return;
}

